spring:
  application:
    name: Config-Default
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
